require("vain.layout.termfair")
require("vain.layout.centerfair")
require("vain.layout.browse")
require("vain.layout.cascadebrowse")
require("vain.layout.uselessfair")
require("vain.layout.gimp")
require("vain.layout.cascade")
module("vain.layout")
